"""empty message

Revision ID: 30c7d02adafb
Revises: 91e34165e265
Create Date: 2019-06-22 18:12:13.990126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c7d02adafb'
down_revision = '91e34165e265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('article', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('article', sa.Column('tags', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tags')
    op.drop_column('article', 'date')
    op.drop_column('article', 'comment_count')
    op.drop_table('user')
    # ### end Alembic commands ###
