"""empty message

Revision ID: 489ad163e768
Revises: 30c7d02adafb
Create Date: 2019-06-24 21:46:16.530177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489ad163e768'
down_revision = '30c7d02adafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('alias', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'alias')
    # ### end Alembic commands ###
