"""empty message

Revision ID: 91e34165e265
Revises: 5cef01290e22
Create Date: 2019-06-22 11:18:48.196652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e34165e265'
down_revision = '5cef01290e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'count')
    # ### end Alembic commands ###
